version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: movies_db
    environment:
      POSTGRES_DB: movies_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: