"""empty message

Revision ID: 0d5fde276915
Revises:
Create Date: 2025-08-22 12:02:36.682086

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0d5fde276915"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("movie", schema=None) as batch_op:
        batch_op.alter_column("date", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("movie", schema=None) as batch_op:
        batch_op.alter_column("date", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###
