"""add source_url

Revision ID: 28ec3c2ca8f6
Revises: 4d53a1ac5dc0
Create Date: 2025-12-06 12:58:15.283809

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "28ec3c2ca8f6"
down_revision: Union[str, Sequence[str], None] = "4d53a1ac5dc0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("movies", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("source_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("movies", schema=None) as batch_op:
        batch_op.drop_column("source_url")

    # ### end Alembic commands ###
